<?php
use Alchemy\Component\Routing\Mapper;
use Alchemy\Component\Routing\Route;
use Alchemy\Component\Routing\Exception\ResourceNotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-30 at 13:05:03.
 */
class MapperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Mapper
     */
    protected $object;
    public static $rootDir = "";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public static function setUpBeforeClass()
    {
        self::$rootDir = realpath(__DIR__ . "/../");

        if (is_dir(self::$rootDir . "/vendor")) {
            require_once self::$rootDir . "/vendor/autoload.php";
        }
    }

    protected function setUp()
    {
        $this->object = new Mapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Mapper::connect
     */
    public function testConnect()
    {
        $mapper = new Mapper();
        $mapper->connect(
            'home_route',
            new Route(
                '/',
                array(
                    '_controller' => 'sample',
                    '_action' => 'index'
                )
            )
        );

        $mapper->connect(
            'to_index_route',
            new Route(
                '/{_controller}',
                array('_action' => 'index')
            )
        );

        $mapper->connect(
            'complete_route',
            new Route(
                '/{_controller}/{_action}'
            )
        );

        $this->assertCount(3, $mapper->getRoutes());

        return $mapper;
    }

    /**
     * @covers Mapper::match
     * @depends testConnect
     */
    public function testMatch(Mapper $mapper)
    {
        //#1
        $url = '/';
        $expected = array(
            '_controller' => 'sample',
            '_action' => 'index'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);

        //#2
        $url = '/my_controller';
        $expected = array(
            '_controller' => 'my_controller',
            '_action' => 'index'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);

        //#3
        $url = '/my_controller/my_action';
        $expected = array(
            '_controller' => 'my_controller',
            '_action' => 'my_action'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);
    }

    /**
     * @expectedException Alchemy\Component\Routing\Exception\ResourceNotFoundException
     * @depends testConnect
     */
    public function testException(Mapper $mapper)
    {
        $url = '/my_controller/my_action/var1/val1';
        $params = $mapper->match($url);
    }

    /**
     * Test cache
     *
     */
    public function testCachedSoure()
    {
        $mapper = new Mapper(new \Alchemy\Component\Yaml\Yaml());
        $mapper->loadFrom(self::$rootDir . "/Tests/fixtures/routes.yaml");

        //#1
        $url = '/';
        $expected = array(
            '_controller' => 'sample',
            '_action' => 'index'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);

        //#2
        $url = '/my_controller';
        $expected = array(
            '_controller' => 'my_controller',
            '_action' => 'index'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);

        //#3
        $url = '/my_controller/my_action';
        $expected = array(
            '_controller' => 'my_controller',
            '_action' => 'my_action'
        );
        $params = $mapper->match($url);
        $this->assertEquals($expected, $params);
    }
}

